version: "3"

services:
  serverpostgres:
    container_name: contract-manager-postgres
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./database-volume:/var/lib/postgresql/data

  serverpgadmin:
    container_name: contract-manager-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "6543:80"
    depends_on:
      - serverpostgres